version: '3.4'

services:
  incrementsequenceapi:
    image: ${DOCKER_REGISTRY-}incrementsequenceapi
    build:
      context: .
      dockerfile: IncrementSequenceApi/Dockerfile
  incrementsequencetest:
    image: ${DOCKER_REGISTRY-}test
    build:
      context: .
      dockerfile: IncrementSequenceTest/Dockerfile